services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mcr.microsoft.com/mssql/server  
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - db-data:/var/opt/mssql/data   
    ports:
      - 1433:1433    
    command: >
      bash -c '
        mkdir -p /var/opt/mssql/data &&
        chown -R mssql:mssql /var/opt/mssql/data &&
        /opt/mssql/bin/sqlservr
      '
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


